// <auto-generated />
using System;
using Metropolis.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Metropolis.Dal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201205131527_AddStreetAndEditActivityToDb")]
    partial class AddStreetAndEditActivityToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Metropolis.DAL.Entities.Activity", b =>
                {
                    b.Property<int>("activityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("activityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("scheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("streetFK")
                        .HasColumnType("int");

                    b.HasKey("activityId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Metropolis.DAL.Entities.Street", b =>
                {
                    b.Property<int>("streetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("alternativeStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("streetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("streetStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("streetId");

                    b.ToTable("Streets");
                });
#pragma warning restore 612, 618
        }
    }
}
